/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as BadgesRouteImport } from './routes/badges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesIndexRouteImport } from './routes/games.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses.$courseId.index'
import { Route as CoursesCourseIdLessonIdRouteImport } from './routes/courses.$courseId.$lessonId'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BadgesRoute = BadgesRouteImport.update({
  id: '/badges',
  path: '/badges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesIndexRoute = GamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdLessonIdRoute = CoursesCourseIdLessonIdRouteImport.update({
  id: '/courses/$courseId/$lessonId',
  path: '/courses/$courseId/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/games/': typeof GamesIndexRoute
  '/courses/$courseId/$lessonId': typeof CoursesCourseIdLessonIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/courses': typeof CoursesIndexRoute
  '/games': typeof GamesIndexRoute
  '/courses/$courseId/$lessonId': typeof CoursesCourseIdLessonIdRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/badges': typeof BadgesRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/courses/': typeof CoursesIndexRoute
  '/games/': typeof GamesIndexRoute
  '/courses/$courseId/$lessonId': typeof CoursesCourseIdLessonIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/badges'
    | '/profile'
    | '/quiz'
    | '/games/$gameId'
    | '/courses/'
    | '/games/'
    | '/courses/$courseId/$lessonId'
    | '/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/badges'
    | '/profile'
    | '/quiz'
    | '/games/$gameId'
    | '/courses'
    | '/games'
    | '/courses/$courseId/$lessonId'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/badges'
    | '/profile'
    | '/quiz'
    | '/games/$gameId'
    | '/courses/'
    | '/games/'
    | '/courses/$courseId/$lessonId'
    | '/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgesRoute: typeof BadgesRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  CoursesCourseIdLessonIdRoute: typeof CoursesCourseIdLessonIdRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/badges': {
      id: '/badges'
      path: '/badges'
      fullPath: '/badges'
      preLoaderRoute: typeof BadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games/'
      preLoaderRoute: typeof GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/$lessonId': {
      id: '/courses/$courseId/$lessonId'
      path: '/courses/$courseId/$lessonId'
      fullPath: '/courses/$courseId/$lessonId'
      preLoaderRoute: typeof CoursesCourseIdLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgesRoute: BadgesRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  CoursesCourseIdLessonIdRoute: CoursesCourseIdLessonIdRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
